doc/build-unix.txt
Add instructions for secp256k1 error :
```
key.cpp:17:23: fatal error: secp256k1.h: No such file or directory
#include <secp256k1.h>
^
compilation terminated.
make: *** [obj/key.o] Error 1
```
=> Add instructions for secp256k1 error on unix

src/chainparams.cpp
Updating to provide more dnsseeds under a single domain. So we dont have to update this code when adding more or Moving dnsseed server.
=> Updating DNSSEED

src/net.cpp
Resolve the following error for user of miniupnpc > 1.6 : 
```
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -DUSE_SECP256K1 -I/root/ION/ion/src -I/root/ION/ion/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/root/ION/ion/src/leveldb/include -I/root/ION/ion/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/net.d -o obj/net.o net.cpp
net.cpp: In function 'void ThreadMapPort()':
net.cpp:1153:74: error: invalid conversion from 'int*' to 'unsigned char' [-fpermissive]
devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
^
net.cpp:1153:74: error: too few arguments to function 'UPNPDev* upnpDiscover(int, const …
```
=> Fix bug for miniupnpc > 1.6

ion-qt.pro
- Ion-Qt: add new GCC compiler hardening options
- Ion-Qt: remove unneeded "--param ssp-buffer-size=1" flag
=> GCC hardening for Ion-Qt

src/darksend.cpp, src/key.cpp, src/masternode.cpp
Fix the two following errors : 
```
key.cpp: In member function ‘bool CKey::SignCompact(const uint256&, std::vector<unsigned char>&) const’:
key.cpp:552:17: warning: unused variable ‘ret’ [-Wunused-variable]
if (int ret = secp256k1_ecdsa_sign_compact(instance_of_csecp256k1.ctx, hash.begin(), &vchSig[1], begin(), secp256k1_nonce_function_rfc6979, NULL, &rec))
^
```
```
key.cpp: In member function ‘bool CPubKey::VerifyCompact(const uint256&, const std::vector<unsigned char>&) const’:
key.cpp:632:10: warning: unused variable ‘fComp’ [-Wunused-variable]
bool fComp = IsCompressed();
^
darksend.cpp: In member function ‘bool CDarkSendPool::IsCollateralValid(const CTransaction&)’:
darksend.cpp:978:29: warning: converting ‘false’ to pointer type ‘bool*’ [-Wconversion-null]
bool* pfMissingInputs = …
```
=> Fix two build warnings

src/chainparams.cpp
https://github.com/bitcoin/bitcoin/commit/a2b04ddfe6452e7d6274f4096bf3f2aee695a6d9
/Users/Jordan/Downloads/ion-1.0.0.0/src/chainparams.cpp:85: error: use of overloaded operator '=' is ambiguous (with operand types 'std::vector<unsigned char>' and 'assign_detail::generic_list<int>')
base58Prefixes[PUBKEY_ADDRESS] = list_of(103);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~
=> Error: use of overloaded operator '=' is ambiguous

build/build.h
This is now included in .gitignore so won’t reappear
=> Remove build folder

src/qt/askpassphrasedialog.cpp
On non-us keyboards you can obtain lower case characters even pressing
the SHIFT, this caused false positives.
=> Improve capslock detection on non-us keyboards

src/qt/forms/overviewpage.ui
This just changes the font size of the word "Wallet"  and "Recent transactions" from 11 to whatever the system default is.
=> Don't specify a point size for "Wallet" and "Recent transactions"

src/secp256k1/build-aux/m4/ax_prog_cc_for_build.m4, src/secp256k1/build-aux/m4/bitcoin_secp.m4
Because it was included in .gitignore it never made it into the initial commit.
Also means we can close #31.
=> Force add the missing src/secp256k1/build-aux/* directory

src/wallet.cpp, src/wallet.h
This harmonizes `CWallet::GetImmatureBalance()` with `CWallet::GetBalance()` and `CWallet::GetUnconfirmedBalance()`.
I've also inadvertently removed a bunch of whitespace so view this commit with **?w=1** at the end of the URL.
=> add CWalletTx::GetImmatureCredit() and use it in CWallet::GetImmatureBalance()

src/miner.cpp
-printpriority is currently ignored without -debug, so I don't see any harm to this.
Reference:
https://github.com/bitcoin/bitcoin/commit/2646080e3dc1a1da5be2c066329eb80e1ca0ef7b
=> Allow -printpriority without -debug

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h
- this allows to setup the trayicon before we have and want a trayicon menu
- should be of great use
- fixes a small bug with the toggleHideAction icon, which is not only used with trayicon but also with the Mac dock
Reference:
https://github.com/bitcoin/bitcoin/commit/f82102121f7c48d94c218af0089a71dde497fa07
=> split of createTrayIconMenu() from createTrayIcon() in BitcoinGUI

ion-qt.pro
- currently we sometimes use "windows" or "win32", but as per https://doc.qt.io/qt-5/qmake-advanced-usage.html, windows seems to be not officially supported (only win32 is mentioned there)
Reference:
https://github.com/bitcoin/bitcoin/pull/2109/commits/7601152ce24b6c9a67335e641a242a0be6888dfe
=> Ion-Qt: ensure all Windows scopes use win32 as identifier

src/qt/optionsmodel.cpp
When compiled with `USE_UPNP=-`, in "Options/Network" tab the "Map port using UPNP" checkbox is set up and disabled, which creates the impression that UPnP is always on.
This patch makes `OptionModel` to always return `false` if UPnP is disabled, which solves this checkbox problem and, IMHO, is much more intuitive behaviour overall. Please review.
It goes from:
To:
Reference:
https://github.com/bitcoin/bitcoin/commit/6a3aef39e70e6da81cbd2484c1721d44f9b02d9a
=> OptionsModel now has MapPortUPnP=false if UPNP is not supported

src/qt/forms/signverifymessagedialog.ui
This fixes the duplicate shortcut usage in sign(alt+s)/verify(alt+v) message dialog.
Reference:
https://github.com/bitcoin/bitcoin/commit/ecd67a142066ba7e5e2a92d152cb8bfb156d6f69
=> Fix duplicate shortcut usage in sign/verify message dialog.

contrib/devtools/README.md, contrib/devtools/git-subtree-check.sh
A script to verify that subtree contents matches upstream subtree.
This is following the LevelDB as subtree commit (#82).
This is the result from git-subtree-check on src/leveldb as part of the LevelDB as subtree commit:
```
$ bash ./contrib/devtools/git-subtree-check.sh src/leveldb
src/leveldb in HEAD was last updated to upstream commit 42dcc7edfc98c50038e4604fa630c626db17bf42 (tree 0519102b1dcd38143ba6a9be45323ff9e2f256fd)
src/leveldb in HEAD currently refers to tree 0519102b1dcd38143ba6a9be45323ff9e2f256fd
GOOD
```
You expect it to say 'GOOD'.
=> Add git-subtree-check.sh script

src/qt/coincontroltreewidget.cpp
Bug description:
1. Run Ion-Qt
2. Open CoinControl
3. Click mouse here(Don't select any input)
4. Press "space"
5. Result
Fix:
this->currentItem() returns the current item in the tree widget and NULL if no selected items.
So we don't try setCheckState for NULL.
Reference:
https://github.com/bitcoin/bitcoin/commit/0eade74c783f670cb69ab982f5a828f7ff5ee0db
=> fix crash: CoinControl "space" bug

src/qt/trafficgraphwidget.cpp, src/qt/trafficgraphwidget.h
Text directly glued on the graph-line looks not so good.
The text currently overlaps the line:
With this PR:
Reference:
https://github.com/bitcoin/bitcoin/commit/93a3f0e7fea8699fca7e062156d7a22293d533b8
=> Qt: Network-Traffic-Graph: make some distance between line and text

src/qt/coincontroldialog.cpp, src/qt/guiutil.cpp, src/qt/guiutil.h, src/qt/masternodemanager.cpp, src/qt/sendcoinsdialog.cpp, src/qt/signverifymessagedialog.cpp
Brings some more consistency back inline with Bitcoin's codebase making future patches easier to port etc.
Don't forget to use `?w=1` at the end of the URL if you don't want to see the whitespace removal changes.
=> Introduce and use GUIUtil::setClipboard() where possible
